return {
	{ "folke/noice.nvim", enabled = false },
	{
		"akinsho/bufferline.nvim",
		event = "VeryLazy",
		dependencies = { "nvim-tree/nvim-web-devicons" },
		opts = {
			options = {
				mode = "buffers",
				always_show_bufferline = true,
				show_buffer_close_icons = false,
				show_close_icon = false,
				separator_style = { "", "" },
				diagnostics = "nvim_lsp",
				offsets = {
					{
						filetype = "neo-tree",
						text = "File Explorer",
						highlight = "Directory",
						separator = true,
					},
				},
			},
			highlights = {
				fill = { bg = "NONE" },
				background = { bg = "NONE", fg = "#4c566a" },
				buffer_visible = { bg = "NONE", fg = "#4c566a" },
				buffer_selected = { bg = "NONE", fg = "#d8dee9", bold = true },
				close_button = { bg = "NONE", fg = "#4c566a" },
				close_button_visible = { bg = "NONE", fg = "#4c566a" },
				close_button_selected = { bg = "NONE", fg = "#d8dee9" },
				separator = { bg = "NONE", fg = "NONE" },
				separator_visible = { bg = "NONE", fg = "NONE" },
				separator_selected = { bg = "NONE", fg = "NONE" },
				tab = { bg = "NONE" },
				tab_selected = { bg = "NONE" },
				tab_close = { bg = "NONE" },
				tab_separator = { bg = "NONE", fg = "NONE" },
				tab_separator_selected = { bg = "NONE", fg = "NONE" },
				duplicate = { bg = "NONE", fg = "#4c566a" },
				duplicate_visible = { bg = "NONE", fg = "#4c566a" },
				duplicate_selected = { bg = "NONE", fg = "#d8dee9" },
				modified = { bg = "NONE", fg = "#ebcb8b" },
				modified_visible = { bg = "NONE", fg = "#ebcb8b" },
				modified_selected = { bg = "NONE", fg = "#ebcb8b" },
				indicator_selected = { bg = "NONE", fg = "#88c0d0" },
				indicator_visible = { bg = "NONE", fg = "#4c566a" },
			},
		},
		keys = {
			{ "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
			{ "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
			{ "<leader>bp", "<cmd>BufferLineTogglePin<cr>", desc = "Pin Buffer" },
			{ "<leader>bc", "<cmd>BufferLinePickClose<cr>", desc = "Pick Close Buffer" },
		},
	},
}
